In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
GPS_injury = pd.read_excel("C:/Users/ferbm/Desktop/Rayados/GPS_injury.xlsx")
GPS_injury.head()

,Unnamed: 0,Date,Distance(m),Dist (m/min),HMLD (m),% ALTA INTENSIDAD,Distance Acc(m),Distance Dec(m),HSR Abs Dist (m),HSR Abs (m/min),...,Mean_PowerM,Std_PowerM,MSWR_PowerM,Player,Talla,Peso,Edad,Rol,prev_injury,Injury
0,134,2021-07-01,2853.192000,62.25,365.031000,0.127938,128.51,0.00,154.638000,3.374,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,NaN
1,135,2021-07-02,0.000000,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,NaN,NaN
2,136,2021-07-03,4332.088000,86.94,838.816000,0.193629,222.42,143.23,178.953000,3.592,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,NaN,NaN
3,137,2021-07-04,3382.301736,109.89,475.035826,0.225926,375.63,259.08,97.706215,7.051,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,NaN,NaN
4,138,2021-07-05,0.000000,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,NaN,NaN

In [3]:
GPS_injury['Date']=pd.to_datetime(GPS_injury['Date'])
GPS_injury['Date'].describe()

<ipython-input-3-3ec7e562dc70>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  GPS_injury['Date'].describe()

count                    2814
unique                    134
top       2021-07-01 00:00:00
freq                       21
first     2021-07-01 00:00:00
last      2021-11-11 00:00:00
Name: Date, dtype: object

In [4]:
GPS_injury.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2814 entries, 0 to 2813
Data columns (total 52 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2814 non-null   int64
 1   Date               2814 non-null   datetime64[ns]
 2   Distance(m)        2814 non-null   float64
 3   Dist (m/min)       2814 non-null   float64
 4   HMLD (m)           2814 non-null   float64
 5   % ALTA INTENSIDAD  2814 non-null   float64
 6   Distance Acc(m)    2814 non-null   float64
 7   Distance Dec(m)    2814 non-null   float64
 8   HSR Abs Dist (m)   2814 non-null   float64
 9   HSR Abs (m/min)    2814 non-null   float64
 10  Sprint Abs(m)      2814 non-null   float64
 11  Sprints ABS        2814 non-null   float64
 12  MAX Speed(km/h)    2814 non-null   float64
 13  Step Balance(%)    2814 non-null   float64
 14  Player Load        2814 non-null   float64
 15  Power met          2814 non-null   float64
 16  duration           2814 non-null   float64
 17  Acute_Dis          2814 non-null   float64
 18  Chronic_Dis        2814 non-null   float64
 19  ACWR_Dis           2814 non-null   float64
 20  EWMA_Dis           2814 non-null   float64
 21  Mean_Dis           2814 non-null   float64
 22  Std_Dis            2814 non-null   float64
 23  MSWR_Dis           2814 non-null   float64
 24  Acute_HMLD         2814 non-null   float64
 25  Chronic_HMLD       2814 non-null   float64
 26  ACWR_HMLD          2814 non-null   float64
 27  EWMA_HMLD          2814 non-null   float64
 28  Mean_HMLD          2814 non-null   float64
 29  Std_HMLD           2814 non-null   float64
 30  MSWR_HMLD          2814 non-null   float64
 31  Acute_HSR          2814 non-null   float64
 32  Chronic_HSR        2814 non-null   float64
 33  ACWR_HSR           2814 non-null   float64
 34  EWMA_HSR           2814 non-null   float64
 35  Mean_HSR           2814 non-null   float64
 36  Std_HSR            2814 non-null   float64
 37  MSWR_HSR           2814 non-null   float64
 38  Acute_PowerM       2814 non-null   float64
 39  Chronic_PowerM     2814 non-null   float64
 40  ACWR_PowerM        2814 non-null   float64
 41  EWMA_PowerM        2814 non-null   float64
 42  Mean_PowerM        2814 non-null   float64
 43  Std_PowerM         2814 non-null   float64
 44  MSWR_PowerM        2814 non-null   float64
 45  Player             2814 non-null   object
 46  Talla              2814 non-null   float64
 47  Peso               2814 non-null   float64
 48  Edad               2814 non-null   int64
 49  Rol                2814 non-null   int64
 50  prev_injury        20 non-null     float64
 51  Injury             11 non-null     float64
dtypes: datetime64[ns](1), float64(47), int64(3), object(1)
memory usage: 1.1+ MB

In [5]:
GPS_injury['Injury'] = GPS_injury['Injury'].fillna(0)
GPS_injury['prev_injury'] = GPS_injury.groupby('Player')['prev_injury'].fillna(method='ffill')
GPS_injury['prev_injury'] = GPS_injury['prev_injury'].fillna(0)

In [6]:
GPS_injury.groupby('Player').Injury.value_counts()

Player              Injury
Alfonso Gonzalez    0.0       134
Axel Grijalva       0.0       133
                    1.0         1
Carlos Rodriguez    0.0       134
Celso Ortiz         0.0       134
Cesar Montes        0.0       133
                    1.0         1
Daniel Parra        0.0       134
Duvan Vergara       0.0       133
                    1.0         1
Edson Gutierrez     0.0       134
Erick Aguirre       0.0       133
                    1.0         1
Gustavo Sanchez     0.0       134
Hector Moreno       0.0       133
                    1.0         1
Jesus Gallardo      0.0       134
Joel Campbell       0.0       133
                    1.0         1
Kaleth Hernandez    0.0       133
                    1.0         1
Matias Kranevitter  0.0       134
Maximiliano Meza    0.0       134
Rogelio Funes Mori  0.0       134
Sebastian Vegas     0.0       133
                    1.0         1
Sergio Villarreal   0.0       133
                    1.0         1
Stefan Medina       0.0       133
                    1.0         1
Vincent Janssen     0.0       133
                    1.0         1
Name: Injury, dtype: int64

In [7]:
GPS_injury.head()

,Unnamed: 0,Date,Distance(m),Dist (m/min),HMLD (m),% ALTA INTENSIDAD,Distance Acc(m),Distance Dec(m),HSR Abs Dist (m),HSR Abs (m/min),...,Mean_PowerM,Std_PowerM,MSWR_PowerM,Player,Talla,Peso,Edad,Rol,prev_injury,Injury
0,134,2021-07-01,2853.192000,62.25,365.031000,0.127938,128.51,0.00,154.638000,3.374,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,0.0
1,135,2021-07-02,0.000000,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,0.0
2,136,2021-07-03,4332.088000,86.94,838.816000,0.193629,222.42,143.23,178.953000,3.592,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,0.0
3,137,2021-07-04,3382.301736,109.89,475.035826,0.225926,375.63,259.08,97.706215,7.051,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,0.0
4,138,2021-07-05,0.000000,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000,...,0.0,0.0,0.0,Alfonso Gonzalez,173.9,71.6,28,2,1.0,0.0

In [8]:
GPS_injury.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2814 entries, 0 to 2813
Data columns (total 52 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2814 non-null   int64
 1   Date               2814 non-null   datetime64[ns]
 2   Distance(m)        2814 non-null   float64
 3   Dist (m/min)       2814 non-null   float64
 4   HMLD (m)           2814 non-null   float64
 5   % ALTA INTENSIDAD  2814 non-null   float64
 6   Distance Acc(m)    2814 non-null   float64
 7   Distance Dec(m)    2814 non-null   float64
 8   HSR Abs Dist (m)   2814 non-null   float64
 9   HSR Abs (m/min)    2814 non-null   float64
 10  Sprint Abs(m)      2814 non-null   float64
 11  Sprints ABS        2814 non-null   float64
 12  MAX Speed(km/h)    2814 non-null   float64
 13  Step Balance(%)    2814 non-null   float64
 14  Player Load        2814 non-null   float64
 15  Power met          2814 non-null   float64
 16  duration           2814 non-null   float64
 17  Acute_Dis          2814 non-null   float64
 18  Chronic_Dis        2814 non-null   float64
 19  ACWR_Dis           2814 non-null   float64
 20  EWMA_Dis           2814 non-null   float64
 21  Mean_Dis           2814 non-null   float64
 22  Std_Dis            2814 non-null   float64
 23  MSWR_Dis           2814 non-null   float64
 24  Acute_HMLD         2814 non-null   float64
 25  Chronic_HMLD       2814 non-null   float64
 26  ACWR_HMLD          2814 non-null   float64
 27  EWMA_HMLD          2814 non-null   float64
 28  Mean_HMLD          2814 non-null   float64
 29  Std_HMLD           2814 non-null   float64
 30  MSWR_HMLD          2814 non-null   float64
 31  Acute_HSR          2814 non-null   float64
 32  Chronic_HSR        2814 non-null   float64
 33  ACWR_HSR           2814 non-null   float64
 34  EWMA_HSR           2814 non-null   float64
 35  Mean_HSR           2814 non-null   float64
 36  Std_HSR            2814 non-null   float64
 37  MSWR_HSR           2814 non-null   float64
 38  Acute_PowerM       2814 non-null   float64
 39  Chronic_PowerM     2814 non-null   float64
 40  ACWR_PowerM        2814 non-null   float64
 41  EWMA_PowerM        2814 non-null   float64
 42  Mean_PowerM        2814 non-null   float64
 43  Std_PowerM         2814 non-null   float64
 44  MSWR_PowerM        2814 non-null   float64
 45  Player             2814 non-null   object
 46  Talla              2814 non-null   float64
 47  Peso               2814 non-null   float64
 48  Edad               2814 non-null   int64
 49  Rol                2814 non-null   int64
 50  prev_injury        2814 non-null   float64
 51  Injury             2814 non-null   float64
dtypes: datetime64[ns](1), float64(47), int64(3), object(1)
memory usage: 1.1+ MB

In [9]:
# Saving the data
GPS_injury.to_excel('GPS_injury_complete.xlsx')